/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sew9.worttrainer.mcquenji;

import javafx.application.Application;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        // find more themes in 'atlantafx.base.theme' package
        Application.setUserAgentStylesheet(new PrimerLight().getUserAgentStylesheet());

        // the rest of the code ...
    }
}
